name: miCard
description: "My Card for everyone"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - data/images/profilePic.png

  fonts:
  - family: Orbitron
    fonts:
    - asset: data/fonts/Orbitron-VariableFont_wght.ttf

  - family: Iceberg
    fonts:
      - asset: data/fonts/Iceberg-Regular.ttf

  - family: Rubik Glitch
    fonts:
      - asset: data/fonts/RubikGlitch-Regular.ttf